---
title: "EDA_ok"
author: "Raphaël Morsomme"
date: "February 1, 2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(purrr)

library(tidyverse)
library(reshape)
library(ggplot2)
library(broom)
library(corrplot)

library(ggmap)
library(maps)
library(mapdata)
library(geojsonio) # to read geojson files
library(ggthemes)
library(sf)

my_ggsave <- partial(ggsave, path = "Deliverables_2/Figures", width = 5, height = 3.5)

load("d_clean.RDATA")
d_metro <- read_csv("subway and attractions data/subway_loc.csv") %>% 
  dplyr::rename(latitude = Station.Latitude, longitude = Station.Longitude)
d_attrac <- read.csv("subway and attractions data/attrac_loc.csv")
```



# Plots

```{r length stay}
d_clean %>%
  ggplot(aes(x = minimum_nights)) + 
  geom_density(adjust = 2) +
  geom_vline(xintercept=30, color = "red", size = 0.3, alpha = 0.3) +
  labs(y = NULL, x = "Minimum Number of Nights") +
  scale_x_continuous(breaks=c(0, 7, 14, 30), limits = c(0,50))

my_ggsave("length_stay_density.jpeg")
```

```{r map eda}
d_clean %>%
  mutate(price_high = price < quantile(price, 0.8)) %>%
 
  ggplot(aes(x = longitude, y = latitude)) +
  geom_point(aes(color = price_high), size = 0.9, alpha = 1) +
  
  geom_point(data = d_attrac, color = "green", size = 3) +
  geom_point(data = d_metro, color = "black", size = 3) +
  xlim(-73.93, -73.828) + 
  ylim(40.8, 40.9) +
  theme_map()+ theme(legend.position="bottom") +
  scale_color_brewer(palette = "Set1", name = "Price Category", labels = c("Top 20%", "Bottom 80%"))

my_ggsave("map_eda.jpeg")
```

```{r proximity metro}
d_clean %>%
  sample_frac(1) %>%
  ggplot(aes(x = proximity_metro, y = price_log)) +
  geom_point(size = 0.1, alpha = 0.05) +
  geom_smooth(col = "red", se = FALSE) +
  labs(x = "Proximity to Closest Metro Station", y = "Price (log)")

my_ggsave("log_price_vs_prox_metro.jpeg")
```

```{r proximity attraction}
d_clean %>%
  ggplot(aes(x = proximity_attraction, y = price_log)) +
  geom_point(size = 0.1, alpha = 0.05) +
  geom_smooth(col = "red", se = FALSE) +
  labs(x = "Proximity to Attractions", y = "Price (log)")

my_ggsave("log_price_vs_prox_attr.jpeg")
```

```{r frequency}
d_clean %>%
  ggplot(aes(x = name_host_freq, y = price_log)) +
  geom_point(size = 0.1, alpha = 0.05) +
  geom_smooth(col = "red", se = FALSE) +
  labs(x = "Host Name Frequency", y = "Price (log)")

my_ggsave("log_price_vs_frequency.jpeg")
```

```{r sentiment}
d_clean %>%
  filter(name_listing_sentiment %>% between(-2,2)) %>%
  ggplot(aes(x = name_listing_sentiment, y = price_log)) +
  geom_point(size = 0.1, alpha = 0.05) +
  geom_smooth(col = "red", se = FALSE, method = "lm") +
  labs(x = "Listing Name Sentiment", y = "Price (log)")

my_ggsave("log_price_vs_sentiment.jpeg")
```

# Others

```{r}
ggplot(data = d_clean, aes(x = proximity_metro, y = popularity )) +
  geom_point(size = 0.3, alpha = 0.3) +
  geom_smooth()
my_ggsave("popularity_vs_prox_metro.jpeg")
```

```{r}
ggplot(data = d_clean, aes(x = proximity_metro, y = log(popularity) )) +
  geom_point(size = 0.3, alpha = 0.3) +
  geom_smooth()
my_ggsave("log_popularity_vs_prox_metro.jpeg")
```

```{r}
ggplot(data = d_clean, aes(x = proximity_attraction, y = popularity )) +
  geom_point(size = 0.3, alpha = 0.3)
my_ggsave("popularity_vs_prox_attr.jpeg")
```

```{r}
ggplot(data = d_clean, aes(x = proximity_attraction, y = log(popularity) )) +
  geom_point(size = 0.3, alpha = 0.04) +
  geom_smooth()

my_ggsave("log_popularity_vs_prox_attr.jpeg")
```

```{r}
ggplot(data = d_clean, aes(x = name_host_special, y = price_log, fill = name_host_special)) +
  geom_boxplot()
my_ggsave("log_price_vs_name_spec.jpeg")
```

```{r}
ggplot(data = d_clean, aes(x = name_host_special, y = log(popularity), fill = name_host_special)) +
  geom_boxplot()
my_ggsave("popularity_vs_name_spec.jpeg")
```


