---
title: "EDA"
author: "Ezinne Nwankwo"
date: "1/26/2020"
output: pdf_document
---

```{r libraries, include=FALSE}
library("tidyverse")
library(maps)
```

```{r}

#histogram of log price
d_test %>% 
  ggplot(aes(log(price))) + geom_histogram() + theme_bw()

#histogram of log popularity
d_test %>% 
  ggplot(aes(log(popularity))) + geom_histogram() + theme_bw() 

#neighborhood and price plot
d_test %>% 
  ggplot(aes(x = neighbourhood_group, y = log(price))) +
    geom_boxplot() + 
    theme_bw()


#neighborhood popularity plot
d_test %>% 
  ggplot(aes(x = neighbourhood_group, y = log(popularity))) +
    geom_boxplot() + 
    theme_bw()

#popularity by price\
#there seems to be a decreasing trend in popularity vs price
d_test %>% 
  ggplot(aes(x = log(popularity), y = log(price))) +
    geom_point() + 
    geom_smooth(method="lm", formula=y ~ x)
    theme_bw()
    
#popularity by price and neighborhood
#there seems to be a clear layering in terms of neighborhood groups
d_clean %>% 
  ggplot(aes(x = log(popularity), y = log(price), color = neighbourhood_group)) +
    geom_point(alpha = 0.1) + 
    facet_wrap(.~neighbourhood_group) +
    theme_bw()

#number of reviews by popularity 
d_test %>% 
  ggplot(aes(x = number_of_reviews , y = log(popularity))) +
    geom_point() + 
    geom_smooth(method="lm", formula=y ~ x)
    theme_bw()
    

#number of reviews by pice
d_test %>% 
  ggplot(aes(x = number_of_reviews , y = log(price))) +
    geom_point() + 
    geom_smooth(method="lm", formula=y ~ x)
    theme_bw()

```



```{r maps}

##new york map data
ny_map <- tbl_df(map_data("county", region = "new york"))
head(ny_map)

```

